[package]
name = "myrestaurant"
version = "0.1.0"
edition = "2021"

license = "MIT OR Apache-2.0"
description = "study for crate publish"
homepage = "https://serde.rs/"
repository = "https://github.com/romalin99/myrestaurant"
readme = "README.md"

[dependencies]
